### ISSUE TITLE
Add number of the starting elements to element info

### ISSUE THREAD

**Issue by kylepokorski** [rayzchen/pyeod#50] opened 2024-01-07 11:56 UTC
In element info, display the number of starting elements (Air, Earth,Fire,Water) needed to create an element. EoD used to have this feature but it was removed.

**Comment by rayzchen** [comment] 2024-01-07 13:16
this will most likely be a separate command due to it being extra computation separate from the other element data

**Comment by Cheesy-Brik** [comment] 2024-01-08 00:54
Less dynamic duplicate of #14

**Closed by Cheesy-Brik** 2024-01-08 00:54 UTC
