### ISSUE TITLE
(Suggestion) Categories/Queries

### ISSUE THREAD

**Issue by YellowCat25** [rayzchen/pyeod#47] opened 2024-01-06 23:40 UTC
Do I even need to explain these

**Comment by glagy** [comment] 2024-01-07 00:31
If you’re adding queries, can you add a query command that adds all elements you can find by only combining the elements in a specific query together, because with normal EoDE queries this is impossible

**Comment by rayzchen** [comment] 2024-01-07 00:35
very computationally expensive

**Comment by Cheesy-Brik** [comment] 2024-01-07 00:53
Duplicate of #6 and #5

**Closed by Cheesy-Brik** 2024-01-07 00:53 UTC
