### ISSUE TITLE
More element leaderboards

### ISSUE THREAD

**Issue by srimpsrimp** [rayzchen/pyeod#70] opened 2024-01-19 10:02 UTC
no idea if this data is stored, but if it is, leaderboards for elements with the most combos that result in them, and elements found by the most people

**Comment by rayzchen** [comment] 2024-01-19 16:53
duplicate of #68

**Closed by rayzchen** 2024-01-19 16:53 UTC

**Comment by rayzchen** [comment] 2024-01-19 16:55
also the 2nd one is kinda useless, because all the low tree size elements will be at the beginning and all the obscure elements are at the end

though once cats are made it'll be more useful
