### ISSUE TITLE
Allow sorting of inventories (by tree size, complexity, etc.)

### ISSUE THREAD

**Issue by srimpsrimp** [rayzchen/pyeod#39] opened 2024-01-05 17:57 UTC
pretty self explanatory, an option to sort your inventory in the slash command like in EoD, by tree size, complexity, name, id, length, maybe even other things like amount of uses or recipes. should also be applied to categories and autocats whenever added

**Comment by rayzchen** [comment] 2024-01-06 00:49
duplicate of #23

**Closed by rayzchen** 2024-01-06 00:49 UTC
Labels: feature
